### ISSUE TITLE
App is crashing every time and not opening

### ISSUE THREAD

**Issue by NikunjKhangwal** [AChep/keyguard-app#293]
The app is crashing for me every time i try to open it, either by app icon or autofill

```
FATAL EXCEPTION: main
Process: com.artemchep.keyguard, PID: 23845
android.database.sqlite.SQLiteException: file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
	at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
	at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(Unknown Source:21)
	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLong(Unknown Source:10)
	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SourceFile:14)
	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SourceFile:2)
	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(Unknown Source:6)
	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SourceFile:4)
	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SourceFile:2)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(Unknown Source:5)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(Unknown Source:0)
	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SourceFile:7)
	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(Unknown Source:137)
	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SourceFile:3)
	at net.zetetic.database.sqlcipher.SupportHelper.getWritableDatabase(Unknown Source:2)
	at X.Z.invoke(Unknown Source:85)
	at Ve.m.getValue(Unknown Source:20)
	at l3.g.i(Unknown Source:2)
	at E.p.r(Unknown Source:27)
	at O3.c.k(Unknown Source:87)
	at bf.a.A(Unknown Source:8)
	at Gg.P.run(Unknown Source:104)
	at Gg.a0.l0(Unknown Source:138)
	at c7.V1.p(Unknown Source:104)
	at j.g.run(Unknown Source:1001)
	at b1.K.run(Unknown Source:496)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: Lg.h: [D0{Cancelling}@a6d524e, Dispatchers.Main.immediate]
	Suppressed: Lg.h: [D0{Cancelling}@f91c47c, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@550455a, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@274ac68, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@f3d5d26, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@c1c2714, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@d9225b2, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@e1ea080, Dispatchers.Default]
	Suppressed: Lg.h: [D0{Cancelling}@bf8eafe, Dispatchers.Default]
```

**Comment by NikunjKhangwal** [comment]
It did, Thanks. This was happening only recently, probably after recent update.
