### ISSUE TITLE
Keystore key generation failed

### ISSUE THREAD

**Issue by littleluoCode** [AChep/keyguard-app#337]
BiometricUnlocking point out "Keystore key generation failed"BiometricUnlocking point out "Keystore key generation failed"

**Comment by littleluoCode** [comment]
> Does a reboot help?

Doesn't help, yet I can use fingerprint recognition to unlock when using the bitwaren app, this problem has been bugging yo for a long time and I've never been able to find a solution!

**Comment by AChep** [comment]
What's the device & OS version? Are there any system updates available?

**Comment by littleluoCode** [comment]
I'm using an Android device with the latest HyperOS

**Comment by littleluoCode** [comment]
![正在上传 Screenshot_2024-05-13-05-36-21-465_com.artemchep.keyguard.jpg…]()

![正在上传 Screenshot_2024-05-13-05-41-19-899_com.artemchep.keyguard.jpg…]()

**Comment by littleluoCode** [comment]
![Screenshot_2024-05-13-05-36-21-465_com.artemchep.keyguard.jpg](https://github.com/AChep/keyguard-app/assets/79254768/c7cc6d41-cc0c-46bb-ab66-7d7ee2d5f498)
![Screenshot_2024-05-13-05-41-19-899_com.artemchep.keyguard.jpg](https://github.com/AChep/keyguard-app/assets/79254768/79e61f0b-8c79-4f05-b75f-4e1b164986e3)

**Comment by mahmoudk1000** [comment]
I get that same problem as well.

**Comment by TigerBeanst** [comment]
Same Problem here.
Here is the log @AChep 
Using the latest version from GitHub
```
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: 23116PN5BC
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 31284
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.artemchep.keyguard
[Version Name]: 1.5.0
[Version Code]: 122240006
[Target SDK]: 34
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-08-12T21:13:37.329
[Stack Trace]:
java.security.GeneralSecurityException: Keystore key generation failed
	at i3.f.a(Unknown Source:225)
	at Oe.c.c(Unknown Source:27)
	at Oe.a.n(Unknown Source:54)
	at Oe.a.invoke(Unknown Source:36)
	at Pe.h.b(Unknown Source:104)
	at A6.l1.n(Unknown Source:1794)
	at A6.l1.invoke(Unknown Source:737)
	at Pe.e.d(Unknown Source:111)
	at Pe.a.n(Unknown Source:28)
	at fg.a.w(Unknown Source:8)
	at Ph.P.run(Unknown Source:112)
	at wc.a.h(Unknown Source:5)
	at wc.a.run(Unknown Source:88)
	at Wh.j.run(Unknown Source:2)
	at Wh.a.run(Unknown Source:95)
	Suppressed: Uh.g: [D0{Cancelling}@f5ce164, Dispatchers.Default]
Caused by: java.security.ProviderException: Keystore key generation failed
	at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:413)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at i3.f.a(Unknown Source:214)
	... 14 more
Caused by: android.security.KeyStoreException: Not implemented (internal Keystore code: -100 message: system/security/keystore2/src/security_level.rs:622

Caused by:
    0: system/security/keystore2/src/security_level.rs:620: While generating Key without explicit attestation key.
    1: Error::Km(r#UNIMPLEMENTED)) (public error code: 12 internal Keystore code: -100)
	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:386)
	at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
	at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:145)
	at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:400)
	... 16 more
```
