### ISSUE TITLE
404's when trying to sign into Bitwarden account on Linux

### ISSUE THREAD

**Issue by Red6785** [AChep/keyguard-app#528]
Today, I changed my master password, enabled 2FA, and changed my encryption settings to Argon2ID (with defaults), but when I try to sign back into my account on Keyguard, it fails. Running Keyguard from the CLI, I can see that when I click "Sign in", this is the output it gives me.

```
404 @ get-prelogin
io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class com.artemchep.keyguard.provider.bitwarden.entity.AccountPreLoginResponse' but was 'class io.ktor.utils.io.ByteBufferChannel'
In response from `https://vault.bitwarden.com/api/accounts/prelogin`
Response status `404 `
Response header `ContentType: null` 
Request header `Accept: application/json`

You can read how to resolve NoTransformationFoundException at FAQ: 
https://ktor.io/docs/faq.html#no-transformation-found-exception
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:94)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.prelogin(login.kt:605)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.access$prelogin(login.kt:1)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt$prelogin$1.invokeSuspend(login.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class com.artemchep.keyguard.provider.bitwarden.entity.ErrorEntity' but was 'class io.ktor.utils.io.ByteBufferChannel'
In response from `https://vault.bitwarden.com/api/accounts/prelogin`
Response status `404 `
Response header `ContentType: null` 
Request header `Accept: application/json`

You can read how to resolve NoTransformationFoundException at FAQ: 
https://ktor.io/docs/faq.html#no-transformation-found-exception
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:94)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.prelogin(login.kt:605)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.access$prelogin(login.kt:1)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt$prelogin$1.invokeSuspend(login.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
com.artemchep.keyguard.common.exception.HttpException: Not Found
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.prelogin(login.kt:642)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.access$prelogin(login.kt:1)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt$prelogin$1.invokeSuspend(login.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Caused by: io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class com.artemchep.keyguard.provider.bitwarden.entity.AccountPreLoginResponse' but was 'class io.ktor.utils.io.ByteBufferChannel'
In response from `https://vault.bitwarden.com/api/accounts/prelogin`
Response status `404 `
Response header `ContentType: null` 
Request header `Accept: application/json`

You can read how to resolve NoTransformationFoundException at FAQ: 
https://ktor.io/docs/faq.html#no-transformation-found-exception
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:94)
        at com.artemchep.keyguard.provider.bitwarden.api.LoginKt.prelogin(login.kt:605)
        ... 8 more

```

**Comment by Red6785** [comment]
Nevermind, my apologies.. Didn't realize my version was out of date.. really should've checked ahead of time.
